[package]
name = "rattish"
version = "0.2.1"
authors = ["Alan Egerton <eggyal@gmail.com>"]
edition = "2018"
description = "Runtime type information for Rust."
repository = "https://github.com/eggyal/rattish"
license = "Apache-2.0"
keywords = ["runtime", "type", "reflection", "rtti", "dynamic"]
categories = ["data-structures", "memory-management", "no-std", "rust-patterns"]

[features]
alloc = []
std = ["alloc"]
static = ["std"]
